### ISSUE TITLE
PlayerEvents dosen't work for Patch v1.1.4.2 (or before)

### ISSUE THREAD

**Issue by se** [ascendedguard/sc2replay-csharp#19]
PlayerEvents dosen't work for Patch v1.1.4.2 (or before). I'm getting always null for return value.

**Comment by ascendedguard** [comment]
This was updated to work better on newer versions, and tested against 1.1.4.2 and 1.1.4.3. It should be better at least for getting the array of events back.

**Comment by se** [comment]
It's still not working. Because all events return "Unknown Event"

**Comment by ascendedguard** [comment]
Unfortunately, this is just about as much as is implemented. Most of the individual events are still missing as I haven't had a good list of event/ability/unit codes, since I can't see them in sc2gears. APM should be approximately correct using the method in the sample application, by counting all events that aren't marked GameEventType.Inactive.
