### ISSUE TITLE
Adding PlayerType.Observer

### ISSUE THREAD

**Issue by keichinger** [ascendedguard/sc2replay-csharp#20]
It'd be really cool if there would be an new PlayerType for Observer, so we can easily filter them out while parsing the replays.

**Comment by ascendedguard** [comment]
Observers aren't added as a Player, since they dont contain the full information as the actual players. As a result, you won't find them in the "Players" array.

That said, I've added a new property, ClientList. This lists all the clients present in the game, and you should be able to figure out the observers by simply removing anyone in the Players list from the ClientList
