### ISSUE TITLE
Player events fail to parse for 1.5.3

### ISSUE THREAD

**Issue by ascendedguard** [ascendedguard/sc2replay-csharp#29]

**Comment by ascendedguard** [comment]
@Mischanix Do you need a separate dumping app to compile the data for your DataCompiler? Otherwise i'm at a loss where to retrieve the "sc2replay.sqlite" necessary for getting the 1.5.3 event information.

**Comment by ghost** [comment]
The intended workflow for patching data is:
- Run this on the new version while it is loaded into a game:  https://gist.github.com/3779650
- You must update the offset, which you can scan for with this pattern, using CheatEngine or a similar tool, and look for the most prevalent occurrence in the beginning executable section of the program.  The address of the discovered offset should be relatively consistent across versions, as well:
  
  a1 ?? ?? ?? ?? 8b 80
- The sqlite database path is `sc2replay-csharp/Starcraft2.ReplayParser.DataCompiler`.
- You will get a sql-formatted output which you can use to import into sc2replay.sqlite's `ability_type` and `unit_type` tables as necessary; however, if the indices are the same as the previous version (quite likely across major versions, i.e. 1.4,1.5,etc.), you simply use the `build_info` table to map the build number to the major version's effective build.
- If a new ability is added, edit `abil_info` to correspond to the appropriate array in the SC2 Editor's data display, and update the internal ability enum, `Starcraft2.ReplayParser/AbilityType.cs`.
- If a new unit is added, edit `unit_info` to map the CUnit to a enum name, and update the unit enum, `Starcraft2.ReplayParser/UnitType.cs`.
- To edit the database with a GUI, grab a copy of Mozilla Nightly and install the following addon: https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/.  This greatly simplifies managing the sc2replay.sqlite database.

For 1.5.3, it looks like they changed the security on the pages where the strings are and I can't read them properly with my current libraries.  So, I remade it in cheatengine since it has the correct permissions on its handles (pinvoke wasn't doin it for me).  Anyway, after all that, there were no changes to the indices so I only need bump the build numbers for 1.5.1~3 in the database.

Once the database has been updated, copy it and run DataCompiler on it.  DataCompiler uses the current path for the database directory, so it's easiest to copy the sc2replay.sqlite file to the Debug directory.  Once you've done that, all the .dat files will be in the Debug folder (or current path) as well, ready to be copied to `Starcraft2.ReplayParser/Version`.

Also, just pushed https://github.com/Mischanix/sc2replay-csharp/commit/c55ac38ae183a0673a8cc08cec3b6577d639cc92
